// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4PAoZZVQsYUhaYjiGAP6DcXDjRwrxerA',
    appId: '1:496628866838:web:15a3fa47ec780d4a46fa37',
    messagingSenderId: '496628866838',
    projectId: 'test-2eef6',
    authDomain: 'test-2eef6.firebaseapp.com',
    storageBucket: 'test-2eef6.firebasestorage.app',
    measurementId: 'G-QJ9W7KWF2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXGYY8Yx3SV6C4B0Y84Nj6sAWW3FDkbnQ',
    appId: '1:496628866838:android:9709158dd4007ae246fa37',
    messagingSenderId: '496628866838',
    projectId: 'test-2eef6',
    storageBucket: 'test-2eef6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUM0cBcZwbgueiL-gBf2MRNdT1TXvQvuA',
    appId: '1:496628866838:ios:f9383132a26b08e246fa37',
    messagingSenderId: '496628866838',
    projectId: 'test-2eef6',
    storageBucket: 'test-2eef6.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUM0cBcZwbgueiL-gBf2MRNdT1TXvQvuA',
    appId: '1:496628866838:ios:f9383132a26b08e246fa37',
    messagingSenderId: '496628866838',
    projectId: 'test-2eef6',
    storageBucket: 'test-2eef6.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4PAoZZVQsYUhaYjiGAP6DcXDjRwrxerA',
    appId: '1:496628866838:web:fcc6e885e91b538946fa37',
    messagingSenderId: '496628866838',
    projectId: 'test-2eef6',
    authDomain: 'test-2eef6.firebaseapp.com',
    storageBucket: 'test-2eef6.firebasestorage.app',
    measurementId: 'G-GQQD60L894',
  );

}